import = [
   # "~/.config/alacritty/themes/themes/{theme}.toml"
   "~/.config/alacritty/themes/themes/catppuccin_mocha.toml"
]

live_config_reload = true

[bell]
animation = "EaseOutExpo"
duration = 0

[font.italic]
family = "JetBrainsMono Nerd Font"

[font]
size = 15 

[font.normal]
family= "JetBrainsMono Nerd Font"
style = "Regular"


[window]
decorations = "none"
startup_mode = "Maximized"
opacity = 0.95

[window.padding]
x = 8
y = 0

[env]
term = "xterm-256color"


[shell]
program = "/opt/homebrew/bin/tmux"
args = ["new-session"]
